package com.blaze.controllerview;

import javafx.fxml.FXML;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import com.blaze.thread.Blaze;
import com.blaze.thread.Relogio;
import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;

import javafx.event.ActionEvent;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;

public class PrincipalController {

	
	
	// Uso Comum
	@FXML
	private TextField tfNumerosSorteados;
	@FXML
	private Button btnIniciar;
	@FXML
	private Label lbAviso;
	@FXML
	private TextField tfTotalBrancas;
	@FXML
	private TextField tfTotalPretas;
	@FXML
	private TextField tfTotalVermelhas;
	@FXML
	private TextField tfTempo;
	@FXML
	private CheckBox checkEntradamanial;

	// sequencia cor
	@FXML
	private TextField tfSequenciaCor;
	@FXML
	private TextField tfNumeroSequenciaSalvaCor;
	@FXML
	private TextField tfNumeroSugestaoCor;
	@FXML
	private TextField tfNumeroAcertoCor;
	@FXML
	private TextField tfApostarCor;

	// Soma
	@FXML
	private TextField tfSequenciaSoma;
	@FXML
	private TextField tfNumeroSequenciaSalvaSoma;
	@FXML
	private TextField tfNumeroSugestaoSoma;
	@FXML
	private TextField tfNumeroAcertoSoma;
	@FXML
	private TextField tfApostarSoma;

	public PrincipalController() {

	}

	// Event Listener on Button.onAction
	@FXML
	public void onBtnIniciar(ActionEvent event) {
		
		this.numerosSorteados("Inicio...");

		Relogio relogio = new Relogio(this.tfTempo);
		relogio.start();

		Blaze blaze = new Blaze(this, this.checkEntradamanial);
		blaze.start();

		this.btnIniciar.setDisable(true);

	}

	// Event Listener on Button.onAction
	@FXML
	public void btnRest(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button.onAction
	@FXML
	public void btnSair(ActionEvent event) {
		System.exit(0);
	}

	public void totalBrancas(int total) {

		this.tfTotalBrancas.setText(String.valueOf(total));
	}

	public void totalVermelhas(int total) {

		this.tfTotalVermelhas.setText(String.valueOf(total));
	}

	public void totalPretas(int total) {

		this.tfTotalPretas.setText(String.valueOf(total));
	}
	
	public void numerosSorteados(String msg) {
		this.tfNumerosSorteados.setText(msg);
	}
	
	public void numeroSequenciaSalvaCor(int total) {
		this.tfNumeroSequenciaSalvaCor.setText(String.valueOf(total));
	}
	
	public void sequenciaCor(String msg) {
		this.tfSequenciaCor.setText(msg);
	}
	
	public void numeroSugestaoCor(int total) {
		this.tfNumeroSugestaoCor.setText(String.valueOf(total));
	}
	public void numeroAcertoCor(int total) {
		this.tfNumeroAcertoCor.setText(String.valueOf(total));
	}
	public void apostarCor(String msg) {
		this.tfApostarCor.setText(msg);
	}
	
	

}
